[package]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "simple-shell"
version = "0.0.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "simple_shell"
path = "lib.rs"

[dependencies]
