[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
runner = "qemu-system-riscv64 -machine virt -bios ../bootloader/rustsbi-qemu.bin -nographic -serial mon:stdio -kernel"
rustflags = [
  "-Clink-arg=-T./os/src/linker.ld",
  "-Cforce-frame-pointers=yes",
]

[unstable]
build-std = ["core", "alloc"]
