[build]
target="riscv64gc-unknown-none-elf" # build an ELF executable

[target.riscv64gc-unknown-none-elf]
# start our executable with qemu when running `cargo run`.
runner="qemu-system-riscv64 -m 2G -machine virt -nographic -serial mon:stdio -kernel"

# linker flags
rustflags=["-Clink-arg=-Tmemory.x", "-Clink-arg=-Tlink.x"]
