[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
runner = "qemu-system-riscv64 -smp 2 -m 2G -machine virt -nographic -bios ./bootloader/rustsbi-qemu.bin -serial mon:stdio -kernel"
rustflags = [
  "-Clink-arg=-Tmemory.x", # "-Clink-arg=-Tlink.x",
]

[unstable]
build-std = ["core", "alloc"]
